import Head from 'next/head';

import Link from 'next/link';
import { useEffect, useState } from 'react';
import db from '../firebase/config.js';
import { collection, getDocs } from 'firebase/firestore';
import CarouselHome from '../components/CarouselHome.jsx';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<CarouselHome />
		</>
	);
}
